// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBOdLFQS1px6w1T3bPrlhWe81DM04r9FVg',
    appId: '1:778055199764:web:b1e63b59116b83ad150b01',
    messagingSenderId: '778055199764',
    projectId: 'proyecto-appropa',
    authDomain: 'proyecto-appropa.firebaseapp.com',
    databaseURL: 'https://proyecto-appropa-default-rtdb.firebaseio.com',
    storageBucket: 'proyecto-appropa.appspot.com',
    measurementId: 'G-N4Q6P27QVH',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyB-F5I_9xMml6X1GBDImwbwM-l_2trBcxE',
    appId: '1:778055199764:android:97748133690bc726150b01',
    messagingSenderId: '778055199764',
    projectId: 'proyecto-appropa',
    databaseURL: 'https://proyecto-appropa-default-rtdb.firebaseio.com',
    storageBucket: 'proyecto-appropa.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyB_rGimytK5bT5cx3t9hueLHSV5YMx01DE',
    appId: '1:778055199764:ios:7e681ba0fa1b05e9150b01',
    messagingSenderId: '778055199764',
    projectId: 'proyecto-appropa',
    databaseURL: 'https://proyecto-appropa-default-rtdb.firebaseio.com',
    storageBucket: 'proyecto-appropa.appspot.com',
    iosClientId:
        '778055199764-uhu3gkbo7kidqfl6pcrnebc7sd86b76a.apps.googleusercontent.com',
    iosBundleId: 'com.example.deskLogin',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyB_rGimytK5bT5cx3t9hueLHSV5YMx01DE',
    appId: '1:778055199764:ios:697933f058167555150b01',
    messagingSenderId: '778055199764',
    projectId: 'proyecto-appropa',
    databaseURL: 'https://proyecto-appropa-default-rtdb.firebaseio.com',
    storageBucket: 'proyecto-appropa.appspot.com',
    iosClientId:
        '778055199764-k6070mj2ck7b5vhmnc49b0d9993qf3i8.apps.googleusercontent.com',
    iosBundleId: 'com.example.deskLogin.RunnerTests',
  );
}
